### ISSUE TITLE
Can't currently save Obs on list view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-observations#10]
on elcid-opat
tried on walk-in list where obs modal is on list view
Save button doesn't work

TypeError: Cannot read property 'hour' of undefined
    at save (http://elcid-opat.herokuapp.com/assets/js/opal/services/item.c872dc485b17.js:74:60)
    at Scope.$scope.save (http://elcid-opat.herokuapp.com/assets/js/opal/controllers/edit_item.b79decf544f9.js:83:29)
    at http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:10773:21
    at http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:18981:17
    at Scope.$eval (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:12608:28)
    at Scope.$apply (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:12706:23)
    at HTMLButtonElement.<anonymous> (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:18980:21)
    at HTMLButtonElement.jQuery.event.dispatch (http://elcid-opat.herokuapp.com/assets/js/jquery-1.11.0/jquery.3b80424646a7.js:4624:9)
    at HTMLButtonElement.elemData.handle (http://elcid-opat.herokuapp.com/assets/js/jquery-1.11.0/jquery.3b80424646a7.js:4292:46)angular.28f401490ec3.js:9997 (anonymous function)angular.28f401490ec3.js:7299 (anonymous function)angular.28f401490ec3.js:12708 Scope.$applyangular.28f401490ec3.js:18980 (anonymous function)jquery.3b80424646a7.js:4624 jQuery.event.dispatchjquery.3b80424646a7.js:4292 elemData.handle

**Comment by davidmiller** [comment]
Only on the list view - saves just fine in patient detail view.

**Comment by GabPoll** [comment]
Agree - no save on list view. Saves on patient details view.
